/* This header file is expected to be generated by meson, so we have to
 * create it manually to build igt-gpu-tools for Android.
 * It is okay to modify this file. It is not autogenerated on Android.
 */

#ifndef CONFIG_H
#define CONFIG_H

#define IGT_SRCDIR "/data/local/tmp/igt"
#define IGT_DATADIR "/data/local/tmp/igt"
#define IGT_IMGDIR "/data/local/tmp/igt"
#define IGT_GIT_SHA1 "GIT"
#define PACKAGE_VERSION "IGT_VERSION"

#define HAVE_GETTID 1
#define HAVE_MEMFD_CREATE 1
#define HAVE_LIBGEN_H 1
#define HAVE_LINUX_KD_H 1
#define HAVE_STRUCT_SYSINFO_TOTALRAM 1

#endif /* CONFIG_H */
